### PR TITLE
cleanup: Rename onload-artifacts to onload-clusterlocal

### PR DESCRIPTION
**Pull request by ivatet-amd**
We are contrasting against official Onload images, therefore renaming to onload-clusterlocal.

Suggested-by: Peter Colledge <peter.colledge@amd.com>

### CODE REVIEW

**Comment by ivatet-amd** [comment]
I'm happy to withdraw the PR if anyone objects.

**Review by pcolledg-xilinx — APPROVED** [review]
The `README.md` mentions `onload-runtime` namespace, it would be good to equally mention that `onload-local` is for the in-cluster build pipeline.

**Review by abower-amd — APPROVED** [review]
If it weren't too long I think `-clusterlocal` would convey the scope precisely!

**Comment by ivatet-amd** [comment]
Applied both suggestions, thanks. Meanwhile, I'll rebase and resolve conflicts, and then merge shortly after unless any comments.

**Pull request merged**
